"""empty message

Revision ID: 4c09630ed278
Revises: d5e7d229b707
Create Date: 2022-03-31 18:46:48.778363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c09630ed278'
down_revision = 'd5e7d229b707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userinfo', sa.Column('role', sa.VARCHAR(length=512), nullable=False))
    op.alter_column('userinfo', 'phone',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    op.create_unique_constraint(None, 'userinfo', ['phone'])
    op.create_unique_constraint(None, 'userinfo', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userinfo', type_='unique')
    op.drop_constraint(None, 'userinfo', type_='unique')
    op.alter_column('userinfo', 'phone',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
    op.drop_column('userinfo', 'role')
    # ### end Alembic commands ###
