"""empty message

Revision ID: d5e7d229b707
Revises: fbb0a3fb3360
Create Date: 2022-03-19 18:53:08.129378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5e7d229b707'
down_revision = 'fbb0a3fb3360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['userinfo.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('user_projects_ibfk_2', 'user_projects', type_='foreignkey')
    op.drop_column('user_projects', 'session_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_projects', sa.Column('session_id', mysql.VARCHAR(length=36), nullable=True))
    op.create_foreign_key('user_projects_ibfk_2', 'user_projects', 'session', ['session_id'], ['session_id'])
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
