"""empty message

Revision ID: fbb0a3fb3360
Revises: 
Create Date: 2022-03-19 18:51:49.284265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbb0a3fb3360'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('project_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('project_name', sa.VARCHAR(length=512), nullable=True),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('userinfo',
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('password', sa.VARCHAR(length=512), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=512), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('session',
    sa.Column('session_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=36), nullable=True),
    sa.Column('project_id', sa.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('certificate',
    sa.Column('certificate_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('certificate_name', sa.VARCHAR(length=512), nullable=True),
    sa.Column('level', sa.VARCHAR(length=64), nullable=True),
    sa.Column('winner', sa.VARCHAR(length=64), nullable=True),
    sa.Column('rank', sa.VARCHAR(length=512), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('giver', sa.VARCHAR(length=512), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('project_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['userinfo.user_id'], ),
    sa.PrimaryKeyConstraint('certificate_id'),
    sa.UniqueConstraint('certificate_id')
    )
    op.create_table('user_projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('project_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['userinfo.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_projects')
    op.drop_table('certificate')
    op.drop_table('session')
    op.drop_table('userinfo')
    op.drop_table('project')
    # ### end Alembic commands ###
